"""new migration

Revision ID: 7c1d44771f0d
Revises: 
Create Date: 2023-01-21 21:57:48.946182

"""
import json
import os
from alembic import op
import sqlalchemy as sa
from db.models import user

# revision identifiers, used by Alembic.
revision = '7c1d44771f0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # code to seed the database with the student records
    with open(os.path.join(os.path.dirname(__file__), "../data/students.json")) as f:
        student_data = f.read()
        
    op.bulk_insert(user.User.__tablename__, json.loads(student_data))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
