"""new migrat

Revision ID: a4c4e0e27cba
Revises: dbab7fa8e22c
Create Date: 2023-01-22 00:29:47.606655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c4e0e27cba'
down_revision = 'dbab7fa8e22c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
