"""new migration

Revision ID: aa9cdcdf7c94
Revises: 7c1d44771f0d
Create Date: 2023-01-22 00:12:59.596917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9cdcdf7c94'
down_revision = '7c1d44771f0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
