"""new migration

Revision ID: dbab7fa8e22c
Revises: aa9cdcdf7c94
Create Date: 2023-01-22 00:23:05.441888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbab7fa8e22c'
down_revision = 'aa9cdcdf7c94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
